apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server.fullname" . }}-conf
data:
  context.xml.tpl:
{{- $contextTemplateFilename := printf "conf/context-%s.xml.tpl" .Values.lifecycle}}
{{- (.Files.Get $contextTemplateFilename) | indent 4 }}