apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.eksRoleArn }}
